// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exception.proto

package com.epsagon.protocol;

public final class ExceptionOuterClass {
  private ExceptionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExceptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.Exception)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>string traceback = 3;</code>
     */
    java.lang.String getTraceback();
    /**
     * <code>string traceback = 3;</code>
     */
    com.google.protobuf.ByteString
        getTracebackBytes();

    /**
     * <code>double time = 4;</code>
     */
    double getTime();

    /**
     * <code>map&lt;string, string&gt; additional_data = 5;</code>
     */
    int getAdditionalDataCount();
    /**
     * <code>map&lt;string, string&gt; additional_data = 5;</code>
     */
    boolean containsAdditionalData(
        java.lang.String key);
    /**
     * Use {@link #getAdditionalDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAdditionalData();
    /**
     * <code>map&lt;string, string&gt; additional_data = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAdditionalDataMap();
    /**
     * <code>map&lt;string, string&gt; additional_data = 5;</code>
     */

    java.lang.String getAdditionalDataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; additional_data = 5;</code>
     */

    java.lang.String getAdditionalDataOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code protocol.Exception}
   */
  public  static final class Exception extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.Exception)
      ExceptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Exception.newBuilder() to construct.
    private Exception(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Exception() {
      type_ = "";
      message_ = "";
      traceback_ = "";
      time_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Exception(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              traceback_ = s;
              break;
            }
            case 33: {

              time_ = input.readDouble();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                additionalData_ = com.google.protobuf.MapField.newMapField(
                    AdditionalDataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              additionalData__ = input.readMessage(
                  AdditionalDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              additionalData_.getMutableMap().put(
                  additionalData__.getKey(), additionalData__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.epsagon.protocol.ExceptionOuterClass.internal_static_protocol_Exception_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetAdditionalData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.epsagon.protocol.ExceptionOuterClass.internal_static_protocol_Exception_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.epsagon.protocol.ExceptionOuterClass.Exception.class, com.epsagon.protocol.ExceptionOuterClass.Exception.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRACEBACK_FIELD_NUMBER = 3;
    private volatile java.lang.Object traceback_;
    /**
     * <code>string traceback = 3;</code>
     */
    public java.lang.String getTraceback() {
      java.lang.Object ref = traceback_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        traceback_ = s;
        return s;
      }
    }
    /**
     * <code>string traceback = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTracebackBytes() {
      java.lang.Object ref = traceback_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceback_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 4;
    private double time_;
    /**
     * <code>double time = 4;</code>
     */
    public double getTime() {
      return time_;
    }

    public static final int ADDITIONAL_DATA_FIELD_NUMBER = 5;
    private static final class AdditionalDataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.epsagon.protocol.ExceptionOuterClass.internal_static_protocol_Exception_AdditionalDataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> additionalData_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAdditionalData() {
      if (additionalData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AdditionalDataDefaultEntryHolder.defaultEntry);
      }
      return additionalData_;
    }

    public int getAdditionalDataCount() {
      return internalGetAdditionalData().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; additional_data = 5;</code>
     */

    public boolean containsAdditionalData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAdditionalData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAdditionalDataMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAdditionalData() {
      return getAdditionalDataMap();
    }
    /**
     * <code>map&lt;string, string&gt; additional_data = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAdditionalDataMap() {
      return internalGetAdditionalData().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; additional_data = 5;</code>
     */

    public java.lang.String getAdditionalDataOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAdditionalData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; additional_data = 5;</code>
     */

    public java.lang.String getAdditionalDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAdditionalData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!getTracebackBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, traceback_);
      }
      if (time_ != 0D) {
        output.writeDouble(4, time_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAdditionalData(),
          AdditionalDataDefaultEntryHolder.defaultEntry,
          5);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!getTracebackBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, traceback_);
      }
      if (time_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, time_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAdditionalData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        additionalData__ = AdditionalDataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, additionalData__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.epsagon.protocol.ExceptionOuterClass.Exception)) {
        return super.equals(obj);
      }
      com.epsagon.protocol.ExceptionOuterClass.Exception other = (com.epsagon.protocol.ExceptionOuterClass.Exception) obj;

      boolean result = true;
      result = result && getType()
          .equals(other.getType());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getTraceback()
          .equals(other.getTraceback());
      result = result && (
          java.lang.Double.doubleToLongBits(getTime())
          == java.lang.Double.doubleToLongBits(
              other.getTime()));
      result = result && internalGetAdditionalData().equals(
          other.internalGetAdditionalData());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + TRACEBACK_FIELD_NUMBER;
      hash = (53 * hash) + getTraceback().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTime()));
      if (!internalGetAdditionalData().getMap().isEmpty()) {
        hash = (37 * hash) + ADDITIONAL_DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAdditionalData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.epsagon.protocol.ExceptionOuterClass.Exception parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epsagon.protocol.ExceptionOuterClass.Exception parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epsagon.protocol.ExceptionOuterClass.Exception parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epsagon.protocol.ExceptionOuterClass.Exception parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epsagon.protocol.ExceptionOuterClass.Exception parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epsagon.protocol.ExceptionOuterClass.Exception parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epsagon.protocol.ExceptionOuterClass.Exception parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.epsagon.protocol.ExceptionOuterClass.Exception parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.epsagon.protocol.ExceptionOuterClass.Exception parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.epsagon.protocol.ExceptionOuterClass.Exception parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.epsagon.protocol.ExceptionOuterClass.Exception parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.epsagon.protocol.ExceptionOuterClass.Exception parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.epsagon.protocol.ExceptionOuterClass.Exception prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.Exception}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.Exception)
        com.epsagon.protocol.ExceptionOuterClass.ExceptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.epsagon.protocol.ExceptionOuterClass.internal_static_protocol_Exception_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetAdditionalData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableAdditionalData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.epsagon.protocol.ExceptionOuterClass.internal_static_protocol_Exception_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.epsagon.protocol.ExceptionOuterClass.Exception.class, com.epsagon.protocol.ExceptionOuterClass.Exception.Builder.class);
      }

      // Construct using com.epsagon.protocol.ExceptionOuterClass.Exception.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = "";

        message_ = "";

        traceback_ = "";

        time_ = 0D;

        internalGetMutableAdditionalData().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.epsagon.protocol.ExceptionOuterClass.internal_static_protocol_Exception_descriptor;
      }

      @java.lang.Override
      public com.epsagon.protocol.ExceptionOuterClass.Exception getDefaultInstanceForType() {
        return com.epsagon.protocol.ExceptionOuterClass.Exception.getDefaultInstance();
      }

      @java.lang.Override
      public com.epsagon.protocol.ExceptionOuterClass.Exception build() {
        com.epsagon.protocol.ExceptionOuterClass.Exception result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.epsagon.protocol.ExceptionOuterClass.Exception buildPartial() {
        com.epsagon.protocol.ExceptionOuterClass.Exception result = new com.epsagon.protocol.ExceptionOuterClass.Exception(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.message_ = message_;
        result.traceback_ = traceback_;
        result.time_ = time_;
        result.additionalData_ = internalGetAdditionalData();
        result.additionalData_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.epsagon.protocol.ExceptionOuterClass.Exception) {
          return mergeFrom((com.epsagon.protocol.ExceptionOuterClass.Exception)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.epsagon.protocol.ExceptionOuterClass.Exception other) {
        if (other == com.epsagon.protocol.ExceptionOuterClass.Exception.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getTraceback().isEmpty()) {
          traceback_ = other.traceback_;
          onChanged();
        }
        if (other.getTime() != 0D) {
          setTime(other.getTime());
        }
        internalGetMutableAdditionalData().mergeFrom(
            other.internalGetAdditionalData());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.epsagon.protocol.ExceptionOuterClass.Exception parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.epsagon.protocol.ExceptionOuterClass.Exception) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object traceback_ = "";
      /**
       * <code>string traceback = 3;</code>
       */
      public java.lang.String getTraceback() {
        java.lang.Object ref = traceback_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          traceback_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string traceback = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTracebackBytes() {
        java.lang.Object ref = traceback_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          traceback_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string traceback = 3;</code>
       */
      public Builder setTraceback(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        traceback_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string traceback = 3;</code>
       */
      public Builder clearTraceback() {
        
        traceback_ = getDefaultInstance().getTraceback();
        onChanged();
        return this;
      }
      /**
       * <code>string traceback = 3;</code>
       */
      public Builder setTracebackBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        traceback_ = value;
        onChanged();
        return this;
      }

      private double time_ ;
      /**
       * <code>double time = 4;</code>
       */
      public double getTime() {
        return time_;
      }
      /**
       * <code>double time = 4;</code>
       */
      public Builder setTime(double value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double time = 4;</code>
       */
      public Builder clearTime() {
        
        time_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> additionalData_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAdditionalData() {
        if (additionalData_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AdditionalDataDefaultEntryHolder.defaultEntry);
        }
        return additionalData_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAdditionalData() {
        onChanged();;
        if (additionalData_ == null) {
          additionalData_ = com.google.protobuf.MapField.newMapField(
              AdditionalDataDefaultEntryHolder.defaultEntry);
        }
        if (!additionalData_.isMutable()) {
          additionalData_ = additionalData_.copy();
        }
        return additionalData_;
      }

      public int getAdditionalDataCount() {
        return internalGetAdditionalData().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; additional_data = 5;</code>
       */

      public boolean containsAdditionalData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAdditionalData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAdditionalDataMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAdditionalData() {
        return getAdditionalDataMap();
      }
      /**
       * <code>map&lt;string, string&gt; additional_data = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getAdditionalDataMap() {
        return internalGetAdditionalData().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; additional_data = 5;</code>
       */

      public java.lang.String getAdditionalDataOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAdditionalData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; additional_data = 5;</code>
       */

      public java.lang.String getAdditionalDataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAdditionalData().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAdditionalData() {
        internalGetMutableAdditionalData().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; additional_data = 5;</code>
       */

      public Builder removeAdditionalData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAdditionalData().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAdditionalData() {
        return internalGetMutableAdditionalData().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; additional_data = 5;</code>
       */
      public Builder putAdditionalData(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAdditionalData().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; additional_data = 5;</code>
       */

      public Builder putAllAdditionalData(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAdditionalData().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.Exception)
    }

    // @@protoc_insertion_point(class_scope:protocol.Exception)
    private static final com.epsagon.protocol.ExceptionOuterClass.Exception DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.epsagon.protocol.ExceptionOuterClass.Exception();
    }

    public static com.epsagon.protocol.ExceptionOuterClass.Exception getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Exception>
        PARSER = new com.google.protobuf.AbstractParser<Exception>() {
      @java.lang.Override
      public Exception parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Exception(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Exception> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Exception> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.epsagon.protocol.ExceptionOuterClass.Exception getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Exception_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Exception_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Exception_AdditionalDataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Exception_AdditionalDataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017exception.proto\022\010protocol\"\304\001\n\tExceptio" +
      "n\022\014\n\004type\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\021\n\ttrac" +
      "eback\030\003 \001(\t\022\014\n\004time\030\004 \001(\001\022@\n\017additional_" +
      "data\030\005 \003(\0132\'.protocol.Exception.Addition" +
      "alDataEntry\0325\n\023AdditionalDataEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\026\n\024com.epsago" +
      "n.protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_Exception_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Exception_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Exception_descriptor,
        new java.lang.String[] { "Type", "Message", "Traceback", "Time", "AdditionalData", });
    internal_static_protocol_Exception_AdditionalDataEntry_descriptor =
      internal_static_protocol_Exception_descriptor.getNestedTypes().get(0);
    internal_static_protocol_Exception_AdditionalDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Exception_AdditionalDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
