// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trace.proto

package com.epsagon.protocol;

public final class TraceOuterClass {
  private TraceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TraceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.Trace)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * customer application name, optional wrapper argument 
     * </pre>
     *
     * <code>string app_name = 1;</code>
     */
    java.lang.String getAppName();
    /**
     * <pre>
     * customer application name, optional wrapper argument 
     * </pre>
     *
     * <code>string app_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppNameBytes();

    /**
     * <code>string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>repeated .protocol.Event events = 3;</code>
     */
    java.util.List<com.epsagon.protocol.EventOuterClass.Event> 
        getEventsList();
    /**
     * <code>repeated .protocol.Event events = 3;</code>
     */
    com.epsagon.protocol.EventOuterClass.Event getEvents(int index);
    /**
     * <code>repeated .protocol.Event events = 3;</code>
     */
    int getEventsCount();
    /**
     * <code>repeated .protocol.Event events = 3;</code>
     */
    java.util.List<? extends com.epsagon.protocol.EventOuterClass.EventOrBuilder> 
        getEventsOrBuilderList();
    /**
     * <code>repeated .protocol.Event events = 3;</code>
     */
    com.epsagon.protocol.EventOuterClass.EventOrBuilder getEventsOrBuilder(
        int index);

    /**
     * <code>repeated .protocol.Exception exceptions = 4;</code>
     */
    java.util.List<com.epsagon.protocol.ExceptionOuterClass.Exception> 
        getExceptionsList();
    /**
     * <code>repeated .protocol.Exception exceptions = 4;</code>
     */
    com.epsagon.protocol.ExceptionOuterClass.Exception getExceptions(int index);
    /**
     * <code>repeated .protocol.Exception exceptions = 4;</code>
     */
    int getExceptionsCount();
    /**
     * <code>repeated .protocol.Exception exceptions = 4;</code>
     */
    java.util.List<? extends com.epsagon.protocol.ExceptionOuterClass.ExceptionOrBuilder> 
        getExceptionsOrBuilderList();
    /**
     * <code>repeated .protocol.Exception exceptions = 4;</code>
     */
    com.epsagon.protocol.ExceptionOuterClass.ExceptionOrBuilder getExceptionsOrBuilder(
        int index);

    /**
     * <code>string version = 5;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 5;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>string platform = 6;</code>
     */
    java.lang.String getPlatform();
    /**
     * <code>string platform = 6;</code>
     */
    com.google.protobuf.ByteString
        getPlatformBytes();
  }
  /**
   * Protobuf type {@code protocol.Trace}
   */
  public  static final class Trace extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.Trace)
      TraceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Trace.newBuilder() to construct.
    private Trace(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Trace() {
      appName_ = "";
      token_ = "";
      events_ = java.util.Collections.emptyList();
      exceptions_ = java.util.Collections.emptyList();
      version_ = "";
      platform_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Trace(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              appName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                events_ = new java.util.ArrayList<com.epsagon.protocol.EventOuterClass.Event>();
                mutable_bitField0_ |= 0x00000004;
              }
              events_.add(
                  input.readMessage(com.epsagon.protocol.EventOuterClass.Event.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                exceptions_ = new java.util.ArrayList<com.epsagon.protocol.ExceptionOuterClass.Exception>();
                mutable_bitField0_ |= 0x00000008;
              }
              exceptions_.add(
                  input.readMessage(com.epsagon.protocol.ExceptionOuterClass.Exception.parser(), extensionRegistry));
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              platform_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          events_ = java.util.Collections.unmodifiableList(events_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          exceptions_ = java.util.Collections.unmodifiableList(exceptions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.epsagon.protocol.TraceOuterClass.internal_static_protocol_Trace_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.epsagon.protocol.TraceOuterClass.internal_static_protocol_Trace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.epsagon.protocol.TraceOuterClass.Trace.class, com.epsagon.protocol.TraceOuterClass.Trace.Builder.class);
    }

    private int bitField0_;
    public static final int APP_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object appName_;
    /**
     * <pre>
     * customer application name, optional wrapper argument 
     * </pre>
     *
     * <code>string app_name = 1;</code>
     */
    public java.lang.String getAppName() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * customer application name, optional wrapper argument 
     * </pre>
     *
     * <code>string app_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppNameBytes() {
      java.lang.Object ref = appName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTS_FIELD_NUMBER = 3;
    private java.util.List<com.epsagon.protocol.EventOuterClass.Event> events_;
    /**
     * <code>repeated .protocol.Event events = 3;</code>
     */
    public java.util.List<com.epsagon.protocol.EventOuterClass.Event> getEventsList() {
      return events_;
    }
    /**
     * <code>repeated .protocol.Event events = 3;</code>
     */
    public java.util.List<? extends com.epsagon.protocol.EventOuterClass.EventOrBuilder> 
        getEventsOrBuilderList() {
      return events_;
    }
    /**
     * <code>repeated .protocol.Event events = 3;</code>
     */
    public int getEventsCount() {
      return events_.size();
    }
    /**
     * <code>repeated .protocol.Event events = 3;</code>
     */
    public com.epsagon.protocol.EventOuterClass.Event getEvents(int index) {
      return events_.get(index);
    }
    /**
     * <code>repeated .protocol.Event events = 3;</code>
     */
    public com.epsagon.protocol.EventOuterClass.EventOrBuilder getEventsOrBuilder(
        int index) {
      return events_.get(index);
    }

    public static final int EXCEPTIONS_FIELD_NUMBER = 4;
    private java.util.List<com.epsagon.protocol.ExceptionOuterClass.Exception> exceptions_;
    /**
     * <code>repeated .protocol.Exception exceptions = 4;</code>
     */
    public java.util.List<com.epsagon.protocol.ExceptionOuterClass.Exception> getExceptionsList() {
      return exceptions_;
    }
    /**
     * <code>repeated .protocol.Exception exceptions = 4;</code>
     */
    public java.util.List<? extends com.epsagon.protocol.ExceptionOuterClass.ExceptionOrBuilder> 
        getExceptionsOrBuilderList() {
      return exceptions_;
    }
    /**
     * <code>repeated .protocol.Exception exceptions = 4;</code>
     */
    public int getExceptionsCount() {
      return exceptions_.size();
    }
    /**
     * <code>repeated .protocol.Exception exceptions = 4;</code>
     */
    public com.epsagon.protocol.ExceptionOuterClass.Exception getExceptions(int index) {
      return exceptions_.get(index);
    }
    /**
     * <code>repeated .protocol.Exception exceptions = 4;</code>
     */
    public com.epsagon.protocol.ExceptionOuterClass.ExceptionOrBuilder getExceptionsOrBuilder(
        int index) {
      return exceptions_.get(index);
    }

    public static final int VERSION_FIELD_NUMBER = 5;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 5;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 5;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLATFORM_FIELD_NUMBER = 6;
    private volatile java.lang.Object platform_;
    /**
     * <code>string platform = 6;</code>
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      }
    }
    /**
     * <code>string platform = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appName_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      for (int i = 0; i < events_.size(); i++) {
        output.writeMessage(3, events_.get(i));
      }
      for (int i = 0; i < exceptions_.size(); i++) {
        output.writeMessage(4, exceptions_.get(i));
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, version_);
      }
      if (!getPlatformBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, platform_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appName_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      for (int i = 0; i < events_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, events_.get(i));
      }
      for (int i = 0; i < exceptions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, exceptions_.get(i));
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, version_);
      }
      if (!getPlatformBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, platform_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.epsagon.protocol.TraceOuterClass.Trace)) {
        return super.equals(obj);
      }
      com.epsagon.protocol.TraceOuterClass.Trace other = (com.epsagon.protocol.TraceOuterClass.Trace) obj;

      boolean result = true;
      result = result && getAppName()
          .equals(other.getAppName());
      result = result && getToken()
          .equals(other.getToken());
      result = result && getEventsList()
          .equals(other.getEventsList());
      result = result && getExceptionsList()
          .equals(other.getExceptionsList());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && getPlatform()
          .equals(other.getPlatform());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APP_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getAppName().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      if (getEventsCount() > 0) {
        hash = (37 * hash) + EVENTS_FIELD_NUMBER;
        hash = (53 * hash) + getEventsList().hashCode();
      }
      if (getExceptionsCount() > 0) {
        hash = (37 * hash) + EXCEPTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getExceptionsList().hashCode();
      }
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getPlatform().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.epsagon.protocol.TraceOuterClass.Trace parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epsagon.protocol.TraceOuterClass.Trace parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epsagon.protocol.TraceOuterClass.Trace parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epsagon.protocol.TraceOuterClass.Trace parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epsagon.protocol.TraceOuterClass.Trace parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epsagon.protocol.TraceOuterClass.Trace parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epsagon.protocol.TraceOuterClass.Trace parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.epsagon.protocol.TraceOuterClass.Trace parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.epsagon.protocol.TraceOuterClass.Trace parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.epsagon.protocol.TraceOuterClass.Trace parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.epsagon.protocol.TraceOuterClass.Trace parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.epsagon.protocol.TraceOuterClass.Trace parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.epsagon.protocol.TraceOuterClass.Trace prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.Trace}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.Trace)
        com.epsagon.protocol.TraceOuterClass.TraceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.epsagon.protocol.TraceOuterClass.internal_static_protocol_Trace_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.epsagon.protocol.TraceOuterClass.internal_static_protocol_Trace_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.epsagon.protocol.TraceOuterClass.Trace.class, com.epsagon.protocol.TraceOuterClass.Trace.Builder.class);
      }

      // Construct using com.epsagon.protocol.TraceOuterClass.Trace.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEventsFieldBuilder();
          getExceptionsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        appName_ = "";

        token_ = "";

        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          eventsBuilder_.clear();
        }
        if (exceptionsBuilder_ == null) {
          exceptions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          exceptionsBuilder_.clear();
        }
        version_ = "";

        platform_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.epsagon.protocol.TraceOuterClass.internal_static_protocol_Trace_descriptor;
      }

      @java.lang.Override
      public com.epsagon.protocol.TraceOuterClass.Trace getDefaultInstanceForType() {
        return com.epsagon.protocol.TraceOuterClass.Trace.getDefaultInstance();
      }

      @java.lang.Override
      public com.epsagon.protocol.TraceOuterClass.Trace build() {
        com.epsagon.protocol.TraceOuterClass.Trace result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.epsagon.protocol.TraceOuterClass.Trace buildPartial() {
        com.epsagon.protocol.TraceOuterClass.Trace result = new com.epsagon.protocol.TraceOuterClass.Trace(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.appName_ = appName_;
        result.token_ = token_;
        if (eventsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            events_ = java.util.Collections.unmodifiableList(events_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.events_ = events_;
        } else {
          result.events_ = eventsBuilder_.build();
        }
        if (exceptionsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            exceptions_ = java.util.Collections.unmodifiableList(exceptions_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.exceptions_ = exceptions_;
        } else {
          result.exceptions_ = exceptionsBuilder_.build();
        }
        result.version_ = version_;
        result.platform_ = platform_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.epsagon.protocol.TraceOuterClass.Trace) {
          return mergeFrom((com.epsagon.protocol.TraceOuterClass.Trace)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.epsagon.protocol.TraceOuterClass.Trace other) {
        if (other == com.epsagon.protocol.TraceOuterClass.Trace.getDefaultInstance()) return this;
        if (!other.getAppName().isEmpty()) {
          appName_ = other.appName_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (eventsBuilder_ == null) {
          if (!other.events_.isEmpty()) {
            if (events_.isEmpty()) {
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureEventsIsMutable();
              events_.addAll(other.events_);
            }
            onChanged();
          }
        } else {
          if (!other.events_.isEmpty()) {
            if (eventsBuilder_.isEmpty()) {
              eventsBuilder_.dispose();
              eventsBuilder_ = null;
              events_ = other.events_;
              bitField0_ = (bitField0_ & ~0x00000004);
              eventsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEventsFieldBuilder() : null;
            } else {
              eventsBuilder_.addAllMessages(other.events_);
            }
          }
        }
        if (exceptionsBuilder_ == null) {
          if (!other.exceptions_.isEmpty()) {
            if (exceptions_.isEmpty()) {
              exceptions_ = other.exceptions_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureExceptionsIsMutable();
              exceptions_.addAll(other.exceptions_);
            }
            onChanged();
          }
        } else {
          if (!other.exceptions_.isEmpty()) {
            if (exceptionsBuilder_.isEmpty()) {
              exceptionsBuilder_.dispose();
              exceptionsBuilder_ = null;
              exceptions_ = other.exceptions_;
              bitField0_ = (bitField0_ & ~0x00000008);
              exceptionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getExceptionsFieldBuilder() : null;
            } else {
              exceptionsBuilder_.addAllMessages(other.exceptions_);
            }
          }
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (!other.getPlatform().isEmpty()) {
          platform_ = other.platform_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.epsagon.protocol.TraceOuterClass.Trace parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.epsagon.protocol.TraceOuterClass.Trace) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object appName_ = "";
      /**
       * <pre>
       * customer application name, optional wrapper argument 
       * </pre>
       *
       * <code>string app_name = 1;</code>
       */
      public java.lang.String getAppName() {
        java.lang.Object ref = appName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * customer application name, optional wrapper argument 
       * </pre>
       *
       * <code>string app_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppNameBytes() {
        java.lang.Object ref = appName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * customer application name, optional wrapper argument 
       * </pre>
       *
       * <code>string app_name = 1;</code>
       */
      public Builder setAppName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * customer application name, optional wrapper argument 
       * </pre>
       *
       * <code>string app_name = 1;</code>
       */
      public Builder clearAppName() {
        
        appName_ = getDefaultInstance().getAppName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * customer application name, optional wrapper argument 
       * </pre>
       *
       * <code>string app_name = 1;</code>
       */
      public Builder setAppNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.epsagon.protocol.EventOuterClass.Event> events_ =
        java.util.Collections.emptyList();
      private void ensureEventsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          events_ = new java.util.ArrayList<com.epsagon.protocol.EventOuterClass.Event>(events_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.epsagon.protocol.EventOuterClass.Event, com.epsagon.protocol.EventOuterClass.Event.Builder, com.epsagon.protocol.EventOuterClass.EventOrBuilder> eventsBuilder_;

      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public java.util.List<com.epsagon.protocol.EventOuterClass.Event> getEventsList() {
        if (eventsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(events_);
        } else {
          return eventsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public int getEventsCount() {
        if (eventsBuilder_ == null) {
          return events_.size();
        } else {
          return eventsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public com.epsagon.protocol.EventOuterClass.Event getEvents(int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);
        } else {
          return eventsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public Builder setEvents(
          int index, com.epsagon.protocol.EventOuterClass.Event value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.set(index, value);
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public Builder setEvents(
          int index, com.epsagon.protocol.EventOuterClass.Event.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public Builder addEvents(com.epsagon.protocol.EventOuterClass.Event value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public Builder addEvents(
          int index, com.epsagon.protocol.EventOuterClass.Event value) {
        if (eventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventsIsMutable();
          events_.add(index, value);
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public Builder addEvents(
          com.epsagon.protocol.EventOuterClass.Event.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public Builder addEvents(
          int index, com.epsagon.protocol.EventOuterClass.Event.Builder builderForValue) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public Builder addAllEvents(
          java.lang.Iterable<? extends com.epsagon.protocol.EventOuterClass.Event> values) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, events_);
          onChanged();
        } else {
          eventsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public Builder clearEvents() {
        if (eventsBuilder_ == null) {
          events_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          eventsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public Builder removeEvents(int index) {
        if (eventsBuilder_ == null) {
          ensureEventsIsMutable();
          events_.remove(index);
          onChanged();
        } else {
          eventsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public com.epsagon.protocol.EventOuterClass.Event.Builder getEventsBuilder(
          int index) {
        return getEventsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public com.epsagon.protocol.EventOuterClass.EventOrBuilder getEventsOrBuilder(
          int index) {
        if (eventsBuilder_ == null) {
          return events_.get(index);  } else {
          return eventsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public java.util.List<? extends com.epsagon.protocol.EventOuterClass.EventOrBuilder> 
           getEventsOrBuilderList() {
        if (eventsBuilder_ != null) {
          return eventsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(events_);
        }
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public com.epsagon.protocol.EventOuterClass.Event.Builder addEventsBuilder() {
        return getEventsFieldBuilder().addBuilder(
            com.epsagon.protocol.EventOuterClass.Event.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public com.epsagon.protocol.EventOuterClass.Event.Builder addEventsBuilder(
          int index) {
        return getEventsFieldBuilder().addBuilder(
            index, com.epsagon.protocol.EventOuterClass.Event.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.Event events = 3;</code>
       */
      public java.util.List<com.epsagon.protocol.EventOuterClass.Event.Builder> 
           getEventsBuilderList() {
        return getEventsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.epsagon.protocol.EventOuterClass.Event, com.epsagon.protocol.EventOuterClass.Event.Builder, com.epsagon.protocol.EventOuterClass.EventOrBuilder> 
          getEventsFieldBuilder() {
        if (eventsBuilder_ == null) {
          eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.epsagon.protocol.EventOuterClass.Event, com.epsagon.protocol.EventOuterClass.Event.Builder, com.epsagon.protocol.EventOuterClass.EventOrBuilder>(
                  events_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          events_ = null;
        }
        return eventsBuilder_;
      }

      private java.util.List<com.epsagon.protocol.ExceptionOuterClass.Exception> exceptions_ =
        java.util.Collections.emptyList();
      private void ensureExceptionsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          exceptions_ = new java.util.ArrayList<com.epsagon.protocol.ExceptionOuterClass.Exception>(exceptions_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.epsagon.protocol.ExceptionOuterClass.Exception, com.epsagon.protocol.ExceptionOuterClass.Exception.Builder, com.epsagon.protocol.ExceptionOuterClass.ExceptionOrBuilder> exceptionsBuilder_;

      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public java.util.List<com.epsagon.protocol.ExceptionOuterClass.Exception> getExceptionsList() {
        if (exceptionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(exceptions_);
        } else {
          return exceptionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public int getExceptionsCount() {
        if (exceptionsBuilder_ == null) {
          return exceptions_.size();
        } else {
          return exceptionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public com.epsagon.protocol.ExceptionOuterClass.Exception getExceptions(int index) {
        if (exceptionsBuilder_ == null) {
          return exceptions_.get(index);
        } else {
          return exceptionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public Builder setExceptions(
          int index, com.epsagon.protocol.ExceptionOuterClass.Exception value) {
        if (exceptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExceptionsIsMutable();
          exceptions_.set(index, value);
          onChanged();
        } else {
          exceptionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public Builder setExceptions(
          int index, com.epsagon.protocol.ExceptionOuterClass.Exception.Builder builderForValue) {
        if (exceptionsBuilder_ == null) {
          ensureExceptionsIsMutable();
          exceptions_.set(index, builderForValue.build());
          onChanged();
        } else {
          exceptionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public Builder addExceptions(com.epsagon.protocol.ExceptionOuterClass.Exception value) {
        if (exceptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExceptionsIsMutable();
          exceptions_.add(value);
          onChanged();
        } else {
          exceptionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public Builder addExceptions(
          int index, com.epsagon.protocol.ExceptionOuterClass.Exception value) {
        if (exceptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExceptionsIsMutable();
          exceptions_.add(index, value);
          onChanged();
        } else {
          exceptionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public Builder addExceptions(
          com.epsagon.protocol.ExceptionOuterClass.Exception.Builder builderForValue) {
        if (exceptionsBuilder_ == null) {
          ensureExceptionsIsMutable();
          exceptions_.add(builderForValue.build());
          onChanged();
        } else {
          exceptionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public Builder addExceptions(
          int index, com.epsagon.protocol.ExceptionOuterClass.Exception.Builder builderForValue) {
        if (exceptionsBuilder_ == null) {
          ensureExceptionsIsMutable();
          exceptions_.add(index, builderForValue.build());
          onChanged();
        } else {
          exceptionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public Builder addAllExceptions(
          java.lang.Iterable<? extends com.epsagon.protocol.ExceptionOuterClass.Exception> values) {
        if (exceptionsBuilder_ == null) {
          ensureExceptionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, exceptions_);
          onChanged();
        } else {
          exceptionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public Builder clearExceptions() {
        if (exceptionsBuilder_ == null) {
          exceptions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          exceptionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public Builder removeExceptions(int index) {
        if (exceptionsBuilder_ == null) {
          ensureExceptionsIsMutable();
          exceptions_.remove(index);
          onChanged();
        } else {
          exceptionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public com.epsagon.protocol.ExceptionOuterClass.Exception.Builder getExceptionsBuilder(
          int index) {
        return getExceptionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public com.epsagon.protocol.ExceptionOuterClass.ExceptionOrBuilder getExceptionsOrBuilder(
          int index) {
        if (exceptionsBuilder_ == null) {
          return exceptions_.get(index);  } else {
          return exceptionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public java.util.List<? extends com.epsagon.protocol.ExceptionOuterClass.ExceptionOrBuilder> 
           getExceptionsOrBuilderList() {
        if (exceptionsBuilder_ != null) {
          return exceptionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(exceptions_);
        }
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public com.epsagon.protocol.ExceptionOuterClass.Exception.Builder addExceptionsBuilder() {
        return getExceptionsFieldBuilder().addBuilder(
            com.epsagon.protocol.ExceptionOuterClass.Exception.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public com.epsagon.protocol.ExceptionOuterClass.Exception.Builder addExceptionsBuilder(
          int index) {
        return getExceptionsFieldBuilder().addBuilder(
            index, com.epsagon.protocol.ExceptionOuterClass.Exception.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.Exception exceptions = 4;</code>
       */
      public java.util.List<com.epsagon.protocol.ExceptionOuterClass.Exception.Builder> 
           getExceptionsBuilderList() {
        return getExceptionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.epsagon.protocol.ExceptionOuterClass.Exception, com.epsagon.protocol.ExceptionOuterClass.Exception.Builder, com.epsagon.protocol.ExceptionOuterClass.ExceptionOrBuilder> 
          getExceptionsFieldBuilder() {
        if (exceptionsBuilder_ == null) {
          exceptionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.epsagon.protocol.ExceptionOuterClass.Exception, com.epsagon.protocol.ExceptionOuterClass.Exception.Builder, com.epsagon.protocol.ExceptionOuterClass.ExceptionOrBuilder>(
                  exceptions_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          exceptions_ = null;
        }
        return exceptionsBuilder_;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 5;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 5;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 5;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 5;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 5;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object platform_ = "";
      /**
       * <code>string platform = 6;</code>
       */
      public java.lang.String getPlatform() {
        java.lang.Object ref = platform_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          platform_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string platform = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPlatformBytes() {
        java.lang.Object ref = platform_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          platform_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string platform = 6;</code>
       */
      public Builder setPlatform(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        platform_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string platform = 6;</code>
       */
      public Builder clearPlatform() {
        
        platform_ = getDefaultInstance().getPlatform();
        onChanged();
        return this;
      }
      /**
       * <code>string platform = 6;</code>
       */
      public Builder setPlatformBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        platform_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.Trace)
    }

    // @@protoc_insertion_point(class_scope:protocol.Trace)
    private static final com.epsagon.protocol.TraceOuterClass.Trace DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.epsagon.protocol.TraceOuterClass.Trace();
    }

    public static com.epsagon.protocol.TraceOuterClass.Trace getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trace>
        PARSER = new com.google.protobuf.AbstractParser<Trace>() {
      @java.lang.Override
      public Trace parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Trace(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Trace> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trace> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.epsagon.protocol.TraceOuterClass.Trace getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Trace_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Trace_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013trace.proto\022\010protocol\032\017exception.proto" +
      "\032\013event.proto\"\225\001\n\005Trace\022\020\n\010app_name\030\001 \001(" +
      "\t\022\r\n\005token\030\002 \001(\t\022\037\n\006events\030\003 \003(\0132\017.proto" +
      "col.Event\022\'\n\nexceptions\030\004 \003(\0132\023.protocol" +
      ".Exception\022\017\n\007version\030\005 \001(\t\022\020\n\010platform\030" +
      "\006 \001(\tB\026\n\024com.epsagon.protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.epsagon.protocol.ExceptionOuterClass.getDescriptor(),
          com.epsagon.protocol.EventOuterClass.getDescriptor(),
        }, assigner);
    internal_static_protocol_Trace_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Trace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Trace_descriptor,
        new java.lang.String[] { "AppName", "Token", "Events", "Exceptions", "Version", "Platform", });
    com.epsagon.protocol.ExceptionOuterClass.getDescriptor();
    com.epsagon.protocol.EventOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
